wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.3
    framework: huggingface
    huggingface_version: 4.11.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.8.11
    start_time: 1633153875
    t:
      1:
      - 1
      - 3
      - 5
      - 9
      - 11
      4: 3.8.11
      5: 0.12.3
      6: 4.11.2
      8:
      - 1
      - 3
      - 5
lr:
  desc: null
  value: 0.01
model_name:
  desc: null
  value: google/bert_uncased_L-2_H-128_A-2
